# fly.toml file generated for misty-sun-248 on 2022-09-11T21:58:28+08:00

app = "misty-sun-248"

[[services]]
  internal_port = 9000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = "9000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
