# fly.toml file generated for aged-snowflake-7546 on 2023-01-22T10:10:24+08:00

app = "aged-snowflake-7546"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[[services]]
  internal_port = 9000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 9000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
